name: Release

on:
  release:
    types: [created]

jobs:
  agent:
    name: Agent Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./agent"
          ldflags: "-s -w"
          pre_command: export CGO_ENABLED=0
          binary_name: "recompose-agent"

  coordinator:
    name: Coordinator Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./coordinator"
          ldflags: "-s -w"
          pre_command: export CGO_ENABLED=0
          binary_name: "recompose-coordinator"
